In [85]:
#1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
import numpy as np
a = np.array([n for n in range(10)], dtype=int)
b = np.arange(10)
print('a =',a)
print('b =',b)

a = [0 1 2 3 4 5 6 7 8 9]
b = [0 1 2 3 4 5 6 7 8 9]


In [4]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
zero = np.zeros((3, 3), dtype=int)
print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [18]:
#3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
b = np.random.randint(1,11,size=(5, 5))
print(b)

[[ 7  5  3  5  6]
 [10  7  9  1  6]
 [ 3 10  1  2  5]
 [ 8  4  1  2  4]
 [10  8  6  7  6]]


In [19]:
#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
b = np.random.random((4, 4))
print(b)

[[0.58906469 0.91185476 0.97110469 0.34052424]
 [0.79053294 0.12071145 0.12979969 0.50706686]
 [0.95867117 0.85668846 0.16009355 0.14564996]
 [0.91204422 0.98766145 0.57763846 0.07866346]]


In [35]:
#5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1,11,5)
b = np.random.randint(1,11,5)
print('a =',a,', b =',b)
print('a + b =',a  +b)
print('a - b =',a - b)
print('a * b =',a * b)

a = [ 9  9  8  1 10] , b = [5 1 2 9 1]
a + b = [14 10 10 10 11]
a - b = [ 4  8  6 -8  9]
a * b = [45  9 16  9 10]


In [38]:
#6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a = np.random.randint(10,size=7)
b = np.random.randint(10,size=7)
print('a =',a,', b =',b)
print('скалярний добуток:', np.dot(a, b))

a = [9 6 6 8 8 7 2] , b = [6 3 3 4 3 5 8]
скалярний добуток: 197


In [43]:
#7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
a = np.random.randint(1,11,size=(2, 2))
b = np.random.randint(1,11,size=(2, 3))
try:
    print('a * b =', a * b)
except:
    print("Перемноження неможливо")
a = np.random.randint(1,11,size=(2, 2))
b = np.random.randint(1,11,size=(2, 2))
print('a * b =', a * b)
a = np.random.randint(1,11,size=(2, 3))
b = np.random.randint(1,11,size=(2, 3))
print('a * b =', a * b)

Перемноження неможливо
a * b = [[27 35]
 [12 30]]
a * b = [[10 45 10]
 [49 32 63]]


In [44]:
#8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
b = np.random.randint(1,11,size=(5, 5))
print(b)
a_inv = np.linalg.inv(b)
print(a_inv)

[[ 5  7  3  4  2]
 [ 2  2  8 10 10]
 [ 3  9  3  4  5]
 [ 2  5  8  8  7]
 [ 2  6  7  7  3]]
[[ 0.37458746 -0.07343234 -0.22772277  0.2970297  -0.31848185]
 [-0.09570957 -0.03630363  0.16831683 -0.08910891  0.11221122]
 [ 0.09735974 -0.419967   -0.25742574  0.9009901  -0.33828383]
 [-0.11386139  0.48267327  0.14851485 -1.01980198  0.5990099 ]
 [-0.01980198 -0.02475248  0.06930693  0.25742574 -0.28712871]]


In [49]:
#9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a = np.random.random((5,5))
print('a = ', a)
a_trans = a.T
print('a_trans =',a_trans)

a =  [[0.49098585 0.57890118 0.03821286 0.42256759 0.32126956]
 [0.91597577 0.17530866 0.8932807  0.62381649 0.44281806]
 [0.31830346 0.93429149 0.44381954 0.20885123 0.04789399]
 [0.50879726 0.64819119 0.33527443 0.86996898 0.58258206]
 [0.40722123 0.93098779 0.73565423 0.34334104 0.01647672]]
a_trans = [[0.49098585 0.91597577 0.31830346 0.50879726 0.40722123]
 [0.57890118 0.17530866 0.93429149 0.64819119 0.93098779]
 [0.03821286 0.8932807  0.44381954 0.33527443 0.73565423]
 [0.42256759 0.62381649 0.20885123 0.86996898 0.34334104]
 [0.32126956 0.44281806 0.04789399 0.58258206 0.01647672]]


In [58]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a = np.random.randint(1,11,size=(3, 4))
b = np.random.randint(1,11,size=4)
print('a =',a,'\nb =',b, end='\n'+'*'*20+'\n')
print('a * b =', a * b)

a = [[1 7 5 7]
 [7 7 5 6]
 [1 7 7 6]] 
b = [9 5 4 6]
********************
a * b = [[ 9 35 20 42]
 [63 35 20 36]
 [ 9 35 28 36]]


In [60]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a = np.random.random((2,3))
b = np.random.random(3)
print('a =',a,'\nb =',b, end='\n'+'*'*40+'\n')
print('a * b =', a * b)

a = [[0.15594041 0.02042987 0.73455094]
 [0.16564497 0.44702527 0.07429604]] 
b = [0.32126146 0.47592414 0.31816757]
****************************************
a * b = [[0.05009764 0.00972307 0.23371029]
 [0.05321534 0.21275011 0.02363859]]


In [65]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a = np.random.randint(1,11,size=(2, 2))
b = np.random.randint(1,11,size=(2, 2))
print('a =',a,'\nb =',b, end='\n'+'*'*20+'\n')
print('поєлементне множення a * b =\n', a * b)

a = [[9 1]
 [1 1]] 
b = [[9 3]
 [4 1]]
********************
поєлементне множення a * b =
 [[81  3]
 [ 4  1]]


In [64]:
#13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a = np.random.randint(1,11,size=(2, 2))
b = np.random.randint(1,11,size=(2, 2))
print('a =',a,'\nb =',b, end='\n'+'*'*20+'\n')
c = np.dot(a, b)
print('добуток матриці a та матриці b =\n', c)

a = [[5 5]
 [3 2]] 
b = [[8 8]
 [3 8]]
********************
добуток матриці a та матриці b =
 [[55 80]
 [30 40]]


In [67]:
#14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a = np.random.randint(1,101,size=(5, 5))
print(a)
print('Сумма єлементів матриці =',a.sum())

[[50 47 46 43 71]
 [17 42 57 74 92]
 [10 49 88 31 68]
 [94  8 74 73 94]
 [47 44 88 69 20]]
Сумма єлементів матриці = 1396


In [72]:
#15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a = np.random.randint(1,11,size=(4, 4))
b = np.random.randint(1,11,size=(4, 4))
print('a =',a,'b =', b, sep='\n')
print('a - b =\n', a-b)

a =
[[ 8  6  8  1]
 [ 5  6  7  9]
 [ 2  3 10  3]
 [10  1  5  7]]
b =
[[ 7  4  1  7]
 [10 10  2 10]
 [10  4  4  4]
 [ 6  4  8  1]]
a - b =
 [[ 1  2  7 -6]
 [-5 -4  5 -1]
 [-8 -1  6 -1]
 [ 4 -3 -3  6]]


In [102]:
#16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a = np.random.random((3,3))
print('a =', a, sep='\n')
b = np.array([sum(n) for n in a], dtype=float)
#b=b.T
print('b =', b, sep='\n')

a =
[[0.88655203 0.90427546 0.84382608]
 [0.33007804 0.27045276 0.68987384]
 [0.02628602 0.12216993 0.97428444]]
b =
[2.63465357 1.29040465 1.1227404 ]


In [91]:
#17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a = np.random.randint(1, 11, size=(3, 4))
print('a =', a, sep='\n')

b = np.array([n ** 2 for n in a], dtype=int)
print('b =', b, sep='\n')

a =
[[7 7 8 1]
 [2 4 6 1]
 [4 4 7 1]]
b =
[[49 49 64  1]
 [ 4 16 36  1]
 [16 16 49  1]]


In [81]:
#18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a = np.random.randint(1, 51, size=(4))
print('a =', a)
b = np.array([n ** 0.5 for n in a], dtype=float)
print('b =', b)

a = [48 26 19  7]
b = [6.92820323 5.09901951 4.35889894 2.64575131]
